//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assigment_5_6_Day_Roberts_ASP.NET.Day_Roberts_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Day_Roberts_Service.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EstimateShipping", ReplyAction="http://tempuri.org/IService1/EstimateShippingResponse")]
        double EstimateShipping(string zipCode, double packageWeight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EstimateShipping", ReplyAction="http://tempuri.org/IService1/EstimateShippingResponse")]
        System.Threading.Tasks.Task<double> EstimateShippingAsync(string zipCode, double packageWeight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSalesTax", ReplyAction="http://tempuri.org/IService1/GetSalesTaxResponse")]
        double GetSalesTax(string zipCode, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSalesTax", ReplyAction="http://tempuri.org/IService1/GetSalesTaxResponse")]
        System.Threading.Tasks.Task<double> GetSalesTaxAsync(string zipCode, double amount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Assigment_5_6_Day_Roberts_ASP.NET.Day_Roberts_Service.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Assigment_5_6_Day_Roberts_ASP.NET.Day_Roberts_Service.IService1>, Assigment_5_6_Day_Roberts_ASP.NET.Day_Roberts_Service.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double EstimateShipping(string zipCode, double packageWeight) {
            return base.Channel.EstimateShipping(zipCode, packageWeight);
        }
        
        public System.Threading.Tasks.Task<double> EstimateShippingAsync(string zipCode, double packageWeight) {
            return base.Channel.EstimateShippingAsync(zipCode, packageWeight);
        }
        
        public double GetSalesTax(string zipCode, double amount) {
            return base.Channel.GetSalesTax(zipCode, amount);
        }
        
        public System.Threading.Tasks.Task<double> GetSalesTaxAsync(string zipCode, double amount) {
            return base.Channel.GetSalesTaxAsync(zipCode, amount);
        }
    }
}
